motif.marketing.offer150={init:function(){new motif.Offer150}};
(function(b,f){var c=function(){this.elements={};this.model={};this.templates={};this.templateFunctions={};this.init()};c.fn=c.prototype;c.fn.init=function(){this.initElements();this.initTemplates();this.compileTemplates();this.bindEvents();this.initModel()};c.fn.initElements=function(){this.elements.motifList=b("#motifsLg")};c.fn.initTemplates=function(){this.templates.motifs=b("#motifsTemplate").html()};c.fn.compileTemplates=function(){this.templateFunctions.motifs=Handlebars.compile(this.templates.motifs)};
c.fn.initModel=function(){var a=this.getQParam("lp_motif");this.model.motifs=[{mName:"",url:"biotech-breakthroughs",returns:"",lrgImg:"",wideImg:"",rghtMargin:"",desc:"",arrow:""},{mName:"",url:"low-beta",returns:"",lrgImg:"",wideImg:"",rghtMargin:"rghtMargin",desc:"",arrow:""},{mName:"",url:"tablet-takeover",returns:"",lrgImg:"",wideImg:"",rghtMargin:"",desc:"",arrow:""}];a&&(this.model.motifs[0].url=a);this.getReturns()};c.fn.showPressVideo=function(a){a={href:a,urlType:"youtube",iframe:!0,width:b(window).width()-
20,height:b(window).height()-20,close:""};b.mDialog(a)};c.fn.constructDataUrl=function(){var a="/data/motifs?";b.each(this.model.motifs,function(b,c){a+="name\x3d"+c.url+"\x26"});return a=a.slice(0,-1)};c.fn.getReturns=function(){var a=this,c=this.constructDataUrl()+"\x26view\x3dfull",d=a.model.motifs;b.ajax({url:c,datatype:"json",success:function(c){b.each(c,function(a,c){b.each(d,function(b,d){a==d.url&&(d.mName=c.name,d.desc=c.description,c.largeImageURL&&(d.lrgImg=c.largeImageURL),c.wideImageURL&&
(d.wideImg=c.wideImageURL),c.oneYearReturns?(d.returns=c.oneYearReturns.toFixed(1).toString()+"%",-1<c.oneYearReturns.toFixed(1).toString().indexOf("-")?d.arrow="down":d.arrow="up"):d.returns="--")})});a.elements.motifList.append(a.templateFunctions.motifs(a.model.motifs))},error:function(a,c,d){b(".performance").hide();b("#motifsLg").hide();b(".qdelay").hide()}})};c.fn.validateName=function(a,c){var d=a.data("prev-value"),e=!1;switch(a.val()){case "First Name":case "Last Name":e=!0}c&&a.val()==d||
(a.data("prev-value",a.val()),/^[\s\w\'\.\-]{1,25}$/.test(a.val())&&0<b.trim(a.val()).length&&!1==e?a.next("div").removeClass("invalid").addClass("valid").html("OK"):c?a.next("div").removeClass("valid").html(a.attr("data-message")).show():a.next("div").removeClass("valid").addClass("invalid").html(a.attr("data-message")).show())};c.fn.validateField=function(a,c){var d=!1,e=/^[a-zA-Z0-9._+-]+@[a-zA-Z0-9.-]+\.[a-zA-Z]{2,4}$/,f=/(?=.*[a-zA-Z]+)(?=.*(\d|[`~!@#\$%\^&\*\(\)\-_\+={}\[\]|<>\?,\.\/\\])).{6,20}/;
if(""==b.trim(a.val()))a.next("div").removeClass("valid").addClass("invalid").html("REQUIRED FIELD").show(),b(a).next("div").addClass("invalid");else{switch(a.attr("id")){case "firstName":d=this.validateName(a);break;case "lastName":d=this.validateName(a);break;case "email":e.test(a.val())?b.ajax({url:motif.vars.authBasePath+"/data/vemail",data:{email:a.val()},dataType:"jsonp",jsonp:"callback",jsonpCallback:"callback",success:function(b){b.objectKey?(a.next("div").removeClass("valid").addClass("invalid").html("Email already taken").show(),
d=!1):a.next("div").removeClass("invalid").addClass("valid").html("OK")},error:function(a,b,c){}}):a.next("div").removeClass("valid").addClass("invalid").html("Not a valid email address.");break;case "txtpass":a.next("div").hasClass("valid")||a.next("div").addClass("invalid");break;case "password":f.test(a.val())?a.next("div").removeClass("invalid").addClass("valid").html("OK"):a.next("div").removeClass("valid").html(a.attr("data-message")).show(),a.next("div").hasClass("valid")||a.next("div").addClass("invalid")}d&&
a.next("div").removeClass("invalid").addClass("valid").html("OK").show()}};c.fn.validateForm=function(a){var c=this;b("input").each(function(a){c.validateField(b(this),!0)});if(b(".err").hasClass("invalid"))return a.preventDefault(),!1;document.signupForm.submit()};c.fn.getQParam=function(a){a=a.replace(/[\[]/,"\\[").replace(/[\]]/,"\\]");a=RegExp("[\\?\x26]"+a+"\x3d([^\x26#]*)").exec(location.search);return null===a?"":decodeURIComponent(a[1].replace(/\+/g," "))};c.fn.bindEvents=function(a){var c=
this;b("body").on("click",".overview ",function(){window.location=b(this).attr("data-url")});b("body").on("click",".signUpBtn",function(){c.validateForm()});b("body").on("keypress","input",function(a){13==a.which&&c.validateForm()});b("body").on("focus","input",function(){this.value===b(this).attr("data-value")&&(b(this).val(""),b(this).next("div").html(b(this).attr("data-message")))});b("body").on("blur","input",function(){""===this.value?(b(this).val(b(this).attr("data-value")),b(this).next("div").html("").removeClass("valid").removeClass("invalid")):
(b(this).next("div").html("").removeClass("valid").removeClass("invalid"),c.validateField(b(this)))});b("body").on("focus","#txtpass",function(){b(this).hide();b("#password").show().focus()});b("body").on("blur","#password",function(){""===this.value?(b("#txtpass").show(),b(this).hide()):b(this).show()});b(".prvideo").click(function(a){a.preventDefault();c.showPressVideo(b(this).attr("href"))})};f.motif.Offer150=c})($,window);
